CREATE TABLE IF NOT EXISTS shares (
    token TEXT PRIMARY KEY,
    document_id TEXT NOT NULL UNIQUE,
    is_editable INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(document_id) REFERENCES documents(id) ON DELETE CASCADE
);
